### ISSUE TITLE
No Output in Slack

### ISSUE THREAD

**Issue by jamiegwatkin** [getsentry/sentry-slack#55]
I'm having issues getting Sentry to send any messages to Slack. 

My configuration is almost default, I supplied the Webhook URL and channel, I didn't make any changes around tags. And have not checked 'Include Tags' or 'Include Rules'. When pressing 'Test Configuration' I see the test message in the channel.

Inside my project settings under 'Rules' I have added the following -

![image](https://cloud.githubusercontent.com/assets/10600045/17850381/d35e49da-6854-11e6-9d36-febdaedfdabf.png)

We do get a lot of events in Sentry so I don't think the issue is related to not receiving any events, we are getting emailed new events as well, we're just not getting any output in slack.

I was wondering if anyone had any ideas or could suggest other things to try.

Cheers

**Comment by leoleovich** [comment]
I have the same problem now, hook works fine if I trigger it via curl (message is delivered in channel)
`Sentry 8.1.2`

**Comment by leoleovich** [comment]
Ok, I was configuring "webhooks". If I configure sentry plugin directly - everything work. Version of plugin `0.5.0`

**Comment by akalongman** [comment]
When I am enabling `Include Tags` checkbox, sentry not sends messages in slack. Why?

**Comment by sudoash** [comment]
Also have this issue, regardless of checkboxes selected. Only using Jira and Slack integrations.

**Comment by dcramer** [comment]
It'd be best to use the [community forum](https://forum.sentry.io), as these are likely issues unrelated to the Slack plugin.

**Comment by noxan** [comment]
We had the very same issue just a day ago. Test notifications from the web frontend were delivered while real production notifications went missing. Our sentry instance is deployed as set of docker containers.

The reason of the issue was, that the slack integration was only installed in the `server` container. Installing the integration on the `cron` container solved the issue. I meanwhile installed it also on the `worker` container, not sure if this affected the issue in any way, but for sure won't hurt.

(Using a the same customized docker image for all containers is how we're are going from now on.)

**Comment by jamiegwatkin** [comment]
Interesting, we're using the same container for all three roles so sadly that's not the issue but thanks for the update.

**Comment by MorrisJobke** [comment]
As stated by previous commenters: This is for example solved by restarting the cron/worker after installing the sentry-slack via pip ;)

@jamiegwatkin Does a restart solve the issue for you?

@dcramer I guess this then can be closed.
